### ISSUE TITLE
make produced error on Mac

### ISSUE THREAD

**Issue by psedik** [xrfang/mdv#6]
I followed installation instructions by cloning the repo and run "make" from working directory, but I got the following error:

```
cp verinfo.tpl version.go
sed -i 's/{_BRANCH}/master/' version.go
sed: 1: "version.go": invalid command code v
make: *** [setver] Error 1
```

**Comment by xrfang** [comment]
This bug is due to incompatibility of sed tool.   I programmed mdv on Linux, and all other platforms could be built on linux directly.

It is now fixed for Mac, but for Windows, there is no native "sed" tool.  I'll consider provide pre-built binaries on github later.
